"""
LSTM-Based Motor Health Classifier (PyTorch Version)
======================================================
Stacked LSTM trained directly on raw time-series sensor data.

Run this on your laptop after installing PyTorch:
    pip install torch
    python train_lstm.py

This gives you the actual LSTM model mentioned in your resume.
Trains on the same data/X.npy and data/y.npy generated by generate_data.py.

Author: Rohit Yadav
"""

import numpy as np
import pandas as pd
import os
import json
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    precision_recall_fscore_support
)

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

np.random.seed(42)
torch.manual_seed(42)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class LSTMClassifier(nn.Module):
    """Stacked LSTM: 64 -> 32 -> Dense(16) -> Dense(3)"""
    def __init__(self, input_size=5, hidden1=64, hidden2=32, n_classes=3, dropout=0.2):
        super().__init__()
        self.lstm1 = nn.LSTM(input_size, hidden1, batch_first=True)
        self.dropout1 = nn.Dropout(dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, batch_first=True)
        self.dropout2 = nn.Dropout(dropout)
        self.fc1 = nn.Linear(hidden2, 16)
        self.relu = nn.ReLU()
        self.dropout3 = nn.Dropout(0.3)
        self.fc2 = nn.Linear(16, n_classes)

    def forward(self, x):
        out, _ = self.lstm1(x)
        out = self.dropout1(out)
        out, (h, _) = self.lstm2(out)
        out = self.dropout2(h[-1])
        out = self.relu(self.fc1(out))
        out = self.dropout3(out)
        return self.fc2(out)


def normalize(X_train, *others):
    mean = X_train.mean(axis=(0, 1), keepdims=True)
    std  = X_train.std(axis=(0, 1), keepdims=True) + 1e-8
    return [(X_train - mean) / std] + [(a - mean) / std for a in others], mean.squeeze(), std.squeeze()


def make_loader(X, y, bs, shuffle):
    return DataLoader(
        TensorDataset(torch.tensor(X, dtype=torch.float32),
                      torch.tensor(y, dtype=torch.long)),
        batch_size=bs, shuffle=shuffle)


def train_epoch(model, loader, opt, criterion):
    model.train()
    tot_loss, correct, total = 0.0, 0, 0
    for X, y in loader:
        X, y = X.to(DEVICE), y.to(DEVICE)
        opt.zero_grad()
        out = model(X)
        loss = criterion(out, y)
        loss.backward()
        opt.step()
        tot_loss += loss.item() * X.size(0)
        correct += (out.argmax(1) == y).sum().item()
        total += X.size(0)
    return tot_loss / total, correct / total


def evaluate(model, loader, criterion):
    model.eval()
    tot_loss, correct, total = 0.0, 0, 0
    preds_all, labels_all = [], []
    with torch.no_grad():
        for X, y in loader:
            X, y = X.to(DEVICE), y.to(DEVICE)
            out = model(X)
            loss = criterion(out, y)
            tot_loss += loss.item() * X.size(0)
            p = out.argmax(1)
            correct += (p == y).sum().item()
            total += X.size(0)
            preds_all.append(p.cpu().numpy())
            labels_all.append(y.cpu().numpy())
    return tot_loss / total, correct / total, np.concatenate(preds_all), np.concatenate(labels_all)


def main():
    print("=" * 60)
    print("LSTM Motor Health Classifier — PyTorch Training")
    print("=" * 60)
    print(f"Device: {DEVICE}")

    X = np.load("data/X.npy").astype(np.float32)
    y = np.load("data/y.npy").astype(np.int64)
    print(f"Total: {len(X)} | Shape: {X.shape}")

    X_tv, X_test, y_tv, y_test = train_test_split(X, y, test_size=0.15, random_state=42, stratify=y)
    X_train, X_val, y_train, y_val = train_test_split(X_tv, y_tv, test_size=0.1765, random_state=42, stratify=y_tv)
    print(f"Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

    (X_train_n, X_val_n, X_test_n), mean, std = normalize(X_train, X_val, X_test)
    train_loader = make_loader(X_train_n, y_train, 32, True)
    val_loader   = make_loader(X_val_n, y_val, 64, False)
    test_loader  = make_loader(X_test_n, y_test, 64, False)

    model = LSTMClassifier().to(DEVICE)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"\nLSTM parameters: {n_params:,}")

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)
    criterion = nn.CrossEntropyLoss()

    os.makedirs("models", exist_ok=True)
    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}
    best_val, patience_cnt, patience, epochs = float('inf'), 0, 8, 30

    print("\nTraining...")
    for epoch in range(1, epochs + 1):
        tl, ta = train_epoch(model, train_loader, optimizer, criterion)
        vl, va, _, _ = evaluate(model, val_loader, criterion)
        scheduler.step(vl)
        history['train_loss'].append(tl); history['train_acc'].append(ta)
        history['val_loss'].append(vl); history['val_acc'].append(va)
        print(f"Epoch {epoch:2d}/{epochs} | train_loss={tl:.4f} acc={ta:.4f} | val_loss={vl:.4f} acc={va:.4f}")
        if vl < best_val:
            best_val = vl
            torch.save(model.state_dict(), "models/best_lstm.pt")
            patience_cnt = 0
        else:
            patience_cnt += 1
            if patience_cnt >= patience:
                print(f"Early stopping at epoch {epoch}")
                break

    model.load_state_dict(torch.load("models/best_lstm.pt"))

    print("\n" + "=" * 60)
    print("TEST SET EVALUATION")
    print("=" * 60)
    _, test_acc, y_pred, y_true = evaluate(model, test_loader, criterion)
    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)
    label_names = ['Healthy', 'Degrading', 'Critical']

    print(f"\nAccuracy : {test_acc*100:.2f}%")
    print(f"Precision: {precision*100:.2f}%")
    print(f"Recall   : {recall*100:.2f}%")
    print(f"F1 Score : {f1*100:.2f}%")
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=label_names, digits=4))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))

    np.save("models/feature_mean.npy", mean)
    np.save("models/feature_std.npy", std)

    print(f"\n✓ LSTM model saved: models/best_lstm.pt")
    print("=" * 60)


if __name__ == "__main__":
    main()
